### ISSUE TITLE
jbuild can't resolve ounit after installing

### ISSUE THREAD

**Issue by tcoopman** [andreypopp/esy-ocaml-project#12]
(I'm not sure if this is an error of this example project or an esy bug)

Steps to reproduce:

* I've cloned this package
* Run `esy add @opam/ounit`
* Create a test folder with: `test.ml` and `jbuild`

Contents of `test.ml`:
```ocaml
open OUnit

let suite =
  "Test" >::: [
    "Sanity" >:: (fun _ ->
      assert_equal true true
    );
  ]

let _ = run_test_tt_main suite
```

Contents of `jbuild`
```
(jbuild_version 1)

(executable
 ((name test)
  (public_name test)
  (libraries (lib ounit))))
```

Now when I run `esy build` I get this error: 
```
  → esy-ocaml-project-ounit @ 0.1.0
  → esy-ocaml-project-ounit @ 0.1.0: build failed:

  # COMMAND: jbuilder build
  Error: External library "ounit" not found.
  -> required by "test/jbuild (context default)"
  Hint: try: jbuilder external-lib-deps --missing @install
```

I tried the same thing with alcotest and that worked fine.

**Comment by andreypopp** [comment]
@tcoopman tried and it worked just fine, do you have a repro somewhere accessible? on github?

**Comment by tcoopman** [comment]
I'll create a repo later today. Just one small pointer, the first time I
did `esy add @ocaml/ounit` instead of @opam. Maybe that broke something?

But then I tried again from scratch and it didn't work either.

**Comment by andreypopp** [comment]
No, it shouldn't produce corrupted installations either. Also what's your `esy version`?

**Comment by tcoopman** [comment]
`esy --version`: 0.0.35

This is my package.json:

```
{
  "name": "esy-ocaml-project-ounit",
  "version": "0.1.0",
  "description": "OCaml workflow with Esy",
  "license": "MIT",
  "esy": {
    "build": [
      "jbuilder build"
    ],
    "install": [
      "esy-installer"
    ],
    "buildsInSource": "_build"
  },
  "dependencies": {
    "@esy-ocaml/esy-installer": "^0.0.0",
    "@opam/jbuilder": "^1.0.0-beta14",
    "@opam/lambda-term": "^1.11.0",
    "@opam/lwt": "^3.1.0",
    "@opam/ounit": "*"
  },
  "peerDependencies": {
    "ocaml": "~4.2.3000"
  },
  "devDependencies": {
    "@opam/merlin": "^3.0.3",
    "ocaml": "~4.2.3000"
  }
}
```

**Comment by tcoopman** [comment]
Fixed by using `oUnit` instead of `ounit`. Linux is case sensitive
