### ISSUE TITLE
How to create npm registry of opam packages?

### ISSUE THREAD

**Issue by ul** [andreypopp/esy-ocaml-project#2]
Would you mind explaining how did you build https://opam-npm.andreypopp.com? Did you use https://github.com/yunxing/opam-npm ? I'm struggling with using opam packages in BuckleScript.

**Comment by andreypopp** [comment]
Hi, we've updates the README with the new workflow — no custom registry is required now as opam packages could be installed with `esy install` command. Please take a look at the README and provide feedback if something isn't clear and/or isn't working.

Unfortunately I can't advice on how to use this with BuckleScript yet as I don't have much experience with it.

**Comment by ul** [comment]
I asked at #bucklescript channel on ReasonML discord and they said that packages I want to use should be rebuilt with `bsb`/`bsc`, including their dependencies. I hope I'll be capable to automate `bsconfig.json` generation for opam packages and entire conversion process (though I have no idea at the moment).

Thank you for clarification!
